// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { PostAuthRegisterData, PostAuthRegisterResponse, PostAuthRegisterError, PostAuthLoginData, PostAuthLoginResponse, PostAuthLoginError, GetAuthGithubData, GetAuthGithubResponse, GetAuthGithubCallbackData, GetAuthGithubCallbackResponse, GetAuthGithubCallbackError, PostAuthRefreshData, PostAuthRefreshResponse, PostAuthRefreshError, PostAuthLogoutData, PostAuthLogoutResponse, GetReportsData, GetReportsResponse, PostReportsData, PostReportsResponse, GetReportByDateData, GetReportByDateResponse, PutReportByDateData, PutReportByDateResponse, PutReportByIdData, PutReportByIdResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRegisterData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAuthRegisterResponse, PostAuthRegisterError, ThrowOnError>({
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const postAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAuthLoginResponse, PostAuthLoginError, ThrowOnError>({
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAuthGithub = <ThrowOnError extends boolean = false>(options: Options<GetAuthGithubData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAuthGithubResponse, unknown, ThrowOnError>({
        url: '/auth/github',
        ...options
    });
};

export const getAuthGithubCallback = <ThrowOnError extends boolean = false>(options: Options<GetAuthGithubCallbackData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAuthGithubCallbackResponse, GetAuthGithubCallbackError, ThrowOnError>({
        url: '/auth/github/callback',
        ...options
    });
};

export const postAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAuthRefreshResponse, PostAuthRefreshError, ThrowOnError>({
        url: '/auth/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAuthLogoutResponse, unknown, ThrowOnError>({
        url: '/auth/logout',
        ...options
    });
};

/**
 * All user reports
 */
export const getReports = <ThrowOnError extends boolean = false>(options?: Options<GetReportsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetReportsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/reports',
        ...options
    });
};

/**
 * Create report
 */
export const postReports = <ThrowOnError extends boolean = false>(options: Options<PostReportsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostReportsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/reports',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Report by date
 */
export const getReportByDate = <ThrowOnError extends boolean = false>(options: Options<GetReportByDateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetReportByDateResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/reports/date/{date}',
        ...options
    });
};

/**
 * Put report by date
 */
export const putReportByDate = <ThrowOnError extends boolean = false>(options: Options<PutReportByDateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutReportByDateResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/reports/date/{date}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Put report
 */
export const putReportById = <ThrowOnError extends boolean = false>(options: Options<PutReportByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutReportByIdResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/reports/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};